//
//  BtData.swift
//  carkey
//
//  Created by Shilapi Chen on 9/25/25.
//
import Foundation
import CryptoSwift

enum BleCommandType {
	enum Service {
		static let PhoneAuthRequest = "38C7"
		static let CarAuthResponse = "A857"
	}
	
	enum Subfunc {
		static let AuthRound1 = "0001"
		static let AuthRound2 = "0002"
	}
}

struct E300BleKeyInfoModel {
	var bleMacStr: String       // MAC address from the cloud
	var keyIdHex: String        // Key ID
	var authAesKey: Data         // AES key for authorization
	var controlAesKey: Data?  // Session key for control commands
	var rollData: Data?          // Rolling code
	var randomData1: String?     // Random data from the vehicle
	var randomData2: String     // Random data generated by the app
	var timestamp: String
	
	init(bleMac: String, keyId: String, masterKey: String, keyMasterRandom: String) {
		self.bleMacStr = bleMac.replacingOccurrences(of: ":", with: "").uppercased()
		self.keyIdHex = keyId.ToHexStringFromIntString()
		
		let masterKeyData = masterKey.ToDataFromHexString()!
		let keyMasterRandomData = keyMasterRandom.ToDataFromHexString()!
		self.authAesKey = masterKeyData.xor(withData: keyMasterRandomData)
		
		self.randomData2 = String(Int.random(in: 0...0xFFFFFFFF), radix: 16, uppercase: true)
		self.timestamp = String(Int(Date().timeIntervalSince1970), radix: 16, uppercase: true)
	}
}

extension E300BleKeyInfoModel {
	func GenerateRequest1() -> String{
		// 第一次request是明文
		let service = BleCommandType.Service.PhoneAuthRequest
		let subfunc = BleCommandType.Subfunc.AuthRound1
		
		var payload = "\(service)\(subfunc)00000000\(self.timestamp)\(self.keyIdHex.PadZero(toLength: 8))06000000000000"
		guard let firstPayloadCrc = payload.ToDataFromHexString()?.Crc16Checksum() else {
			loggerBle.error("failed to generate request 1: failed to convert payload to hex")
			return ""
		}
		payload = "\(payload)\(String(firstPayloadCrc, radix: 16, uppercase: true))".PadZeroOnTail(toLength: 64)
		loggerBle.debug("payload generated for request 1: \(payload)")
		
		return payload
	}
	
	func GenerateRequest2() -> String{
		let service = BleCommandType.Service.PhoneAuthRequest
		let subfunc = BleCommandType.Subfunc.AuthRound2
		guard let randomData1 = self.randomData1 else {
			loggerBle.error("failed to fetch random1")
			return ""
		}
		
		var payload = "\(service)\(subfunc)\(self.randomData2)\(randomData1)\(self.keyIdHex.PadZero(toLength: 8))06000000000000"
		guard let firstPayloadCrc = payload.ToDataFromHexString()?.Crc16Checksum() else {
			loggerBle.error("failed to generate request 2 failed to convert payload to hex")
			return ""
		}
		payload = "\(payload)\(String(firstPayloadCrc, radix: 16, uppercase: true))".PadZeroOnTail(toLength: 64)
		loggerBle.error("payload generated for request 2: \(payload)")
		
		// 加密
		do {
			let encryptedPayload = try AES(key: Array(self.authAesKey), blockMode: ECB(), padding: .noPadding).encrypt(Array(Data(hex: payload)))
			loggerBle.debug("payload encrypted for request 2: \(encryptedPayload)")
			return Data(encryptedPayload).toHexString()
		} catch {
			loggerBle.error("payload encrypt error for request2")
			return payload
		}
	}
}
