import Foundation
import SwiftyBluetooth
import CoreBluetooth
import Combine
import SwiftUI
import CommonCrypto

// disconnected -> scanning -> connecting -> authorizing -> connected
enum BluetoothManagerState {
	case unknown
	case disconnected
	case authorizing
	case connected
	case scanning
	
	var description: String {
		switch self {
		case .unknown: return "Unknown"
		case .disconnected: return "Disconnected"
		case .authorizing: return "Authorizing"
		case .connected: return "Connected"
		case .scanning: return "Scanning"
		}
	}
}

extension Peripheral: @retroactive Identifiable {
	public var id: String {
		return self.identifier.uuidString
	}
}

struct E300BleKeyInfoModel {
	var bleMacStr: String?       // MAC address from the cloud
	var keyIdHex: String?        // Key ID
	var aes128Key: Data?         // AES key for authorization
	var controlAes128Key: Data?  // Session key for control commands
	var rollData: Data?          // Rolling code
	var randomData1: String?     // Random data from the vehicle
	var randomData2: String?     // Random data generated by the app
}

struct BleTarget {
	var peripheral: Peripheral
	var authorizeRequestCharacteristic: CBCharacteristic?
	var authorizeResponseCharacteristic: CBCharacteristic?
	var controlRequestCharacteristic: CBCharacteristic?
	var controlResponseCharacteristic: CBCharacteristic?
}

class BluetoothManager: ObservableObject {
	static let shared = BluetoothManager()
	
	@Published var keyInfo: E300BleKeyInfoModel?
	@Published var avaliblePeripherals = [Peripheral]()
	@Published var target: BleTarget?
	@Published var state: BluetoothManagerState = .disconnected
	
	private var authenticationMonitoringTask: Timer?
	private var isFound = false
	
	private init(){
		// Mock key info loading
		self.keyInfo = E300BleKeyInfoModel(
			bleMacStr: "609866F07BEB", // IMPORTANT: Use the correct MAC from your vehicle
			keyIdHex: "01020304",
			aes128Key: "0123456789ABCDEF0123456789ABCDEF".dataFromHexString()!
		)
	}
}

extension BluetoothManager {
	func getState() -> BluetoothManagerState {
		return self.state
	}
	
	func startScan() {
		print("BtThing: scanning start")
		self.state = .scanning
		self.isFound = false
		
		SwiftyBluetooth.scanForPeripherals(withServiceUUIDs: nil, timeoutAfter: 15) { scanResult in
			switch scanResult {
			case .scanStarted:
				self.state = .scanning
			case .scanResult(let peripheral, let advertisementData, _):
				self.onScanMatchCallback(peripheral: peripheral, advertisementData: advertisementData)
			case .scanStopped(let peripherals, let error):
				print("BtThing: scan ended")
				if self.state == .scanning {
					self.state = .disconnected
				}
				self.avaliblePeripherals = peripherals
				if let error = error {
					print("Encountered error during bt scanning: \(error)")
				}
			}
		}
	}
	
	// MARK: - MODIFICATION POINT: Using Manufacturer Data for matching
	private func onScanMatchCallback(peripheral: Peripheral, advertisementData: [String: Any]) {
		guard !isFound,
			  let manufacturerData = advertisementData[CBAdvertisementDataManufacturerDataKey] as? Data,
			  let targetMac = self.keyInfo?.bleMacStr else { return }
		
		let discoveredMac = getMacAddress(from: manufacturerData)
		
		if discoveredMac.uppercased() == targetMac.uppercased() {
			print("BtThing: ble mac matched: \(discoveredMac)")
			self.isFound = true
			SwiftyBluetooth.stopScan()
			
			connectTo(peripheral: peripheral)
		}
	}
	
	private func connectTo(peripheral: Peripheral) {
		peripheral.connect(withTimeout: 5) { result in
			switch result {
			case .success:
				print("BtThing: ble connected to \(peripheral.name ?? "unnamed")")
				self.target = BleTarget(peripheral: peripheral)
				
				NotificationCenter.default.addObserver(self,
													   selector: #selector(self.peripheralDidDisconnect(_:)),
													   name: Peripheral.PeripheralDisconnected,
													   object: peripheral)
				
				// Start the strict, sequential discovery process
				self.startSequentialDiscovery(for: peripheral)
				
			case .failure(let error):
				print("BtThing: failed to connect: \(error)")
				self.state = .disconnected
			}
		}
	}
	
	// MARK: - MODIFICATION POINT: Replaced concurrent discovery with a sequential flow
	private func startSequentialDiscovery(for peripheral: Peripheral) {
		print("BtThing: starting sequential discovery flow...")
		self.state = .authorizing
		
		// Step 1: Discover Authorization Service ONLY
		peripheral.discoverServices(withUUIDs: [SGMWBLEProfile.AuthorizeService.uuid]) { [weak self] result in
			guard let self = self else { return }
			switch result {
			case .success(let services):
				guard let authService = services.first else {
					print("BtThing: unable to find target authorization service, disconnecting")
					self.disconnectPeripheral(peripheral: peripheral)
					return
				}
				// Step 2: Discover Authorization Characteristics ONLY
				self.discoverAuthorizationCharacteristics(for: peripheral, service: authService)
			case .failure(let error):
				print("BtThing: unable to find target services, disconnecting: \(error)")
				self.disconnectPeripheral(peripheral: peripheral)
			}
		}
	}
	
	private func discoverAuthorizationCharacteristics(for peripheral: Peripheral, service: CBService) {
		peripheral.discoverCharacteristics(withUUIDs: SGMWBLEProfile.AuthorizeService.Characteristics.AllCharacteristicsUuid, ofServiceWithUUID: service.uuid) { [weak self] result in
			guard let self = self else { return }
			switch result {
			case .success(let characteristics):
				print("BtThing: discovered authorization characteristics")
				self.assignCharacteristics(characteristics)
				
				// Step 3: If characteristics are found, proceed to enable notifications
				if self.target?.authorizeResponseCharacteristic != nil {
					self.setAllNotification()
					
				} else {
					print("BtThing: did not find all required authorization characteristics, disconnecting")
					self.disconnectPeripheral(peripheral: peripheral)
				}
			case .failure(let error):
				print("BtThing: unable to find target characteristics under authorize service, disconnecting: \(error)")
				self.disconnectPeripheral(peripheral: peripheral)
			}
		}
	}
	
	private func setAllNotification() {
		guard let target = self.target,
			  let authResponseChar = target.authorizeResponseCharacteristic,
			  let controlResponseChar = target.controlResponseCharacteristic
		else { return }
		
		print("BtThing: enabling notifications for authorization and control...")
		
		// Register observer BEFORE enabling notifications
		NotificationCenter.default.addObserver(self,
											   selector: #selector(characteristicValueUpdated(_:)),
											   name: Peripheral.PeripheralCharacteristicValueUpdate,
											   object: target.peripheral)
		
		// Set notify value for auth
		target.peripheral.setNotifyValue(toEnabled: true, ofCharac: authResponseChar) { [weak self] result in
			guard let self = self else { return }
			switch result {
			case .success(let isNotifying) where isNotifying:
				target.peripheral.setNotifyValue(toEnabled: true, ofCharac: authResponseChar) { [weak self] result in
					guard let self = self else { return }
					switch result {
					case .success(let isNotifying) where isNotifying:
						print("BtThing: successfully set notify for authorize")
						// Start a 7-second timer to wait for the car's challenge
						self.authenticationMonitoringTask?.invalidate()
						self.authenticationMonitoringTask = Timer.scheduledTimer(withTimeInterval: 7.0, repeats: false) { _ in
							print("BtThing: Authorization timed out after 7 seconds.")
							self.disconnectPeripheral(peripheral: target.peripheral)
						}
					case .failure(let error):
						print("BtThing: failed to set notify for authorize: \(error)")
						self.disconnectPeripheral(peripheral: target.peripheral)
					default:
						break
					}
				}
			case .failure(let error):
				print("BtThing: failed to set notify for authorize: \(error)")
				self.disconnectPeripheral(peripheral: target.peripheral)
			default:
				break
			}
		}
		
		// Set notify value for control
		target.peripheral.setNotifyValue(toEnabled: true, ofCharac: controlResponseChar) { [weak self] result in
			guard let self = self else { return }
			switch result {
			case .success(let isNotifying) where isNotifying:
				target.peripheral.setNotifyValue(toEnabled: true, ofCharac: controlResponseChar) { [weak self] result in
					guard let self = self else { return }
					switch result {
					case .success(let isNotifying) where isNotifying:
						print("BtThing: successfully set notify for control")
					case .failure(let error):
						print("BtThing: failed to set notify for control: \(error)")
						self.disconnectPeripheral(peripheral: target.peripheral)
					default:
						break
					}
				}
			case .failure(let error):
				print("BtThing: failed to set notify for control: \(error)")
				self.disconnectPeripheral(peripheral: target.peripheral)
			default:
				break
			}
		}
	}
	
	@objc private func characteristicValueUpdated(_ notification: Notification) {
		authenticationMonitoringTask?.invalidate() // Got a response, cancel timeout timer
		authenticationMonitoringTask = nil
		
		guard let characteristic = notification.userInfo?["characteristic"] as? CBCharacteristic,
			  let data = characteristic.value else {
			print("BtThing: received notification with no characteristic or value")
			return
		}
		
		print("BtThing: received notification for characteristic: \(characteristic.uuid.uuidString)")
		
		if characteristic.uuid == SGMWBLEProfile.AuthorizeService.Characteristics.Response.CBUUIDRepresentation {
			authorizeRequestCallback(data: data)
		}
	}
	
	private func authorizeRequestCallback(data: Data) {
		guard self.keyInfo != nil, let key = self.keyInfo!.aes128Key else { return }
		
		guard let ucuFrame = UcuAuthorizationRequestFrame(dataFrame: data, key: key) else {
			print("BtThing: decode car authorization data failed")
			self.disconnectPeripheral(peripheral: self.target?.peripheral)
			return
		}
		
		if ucuFrame.serviceId == "A857" && ucuFrame.subfunction == "0001" {
			print("[Validation] Step B: Received UCU challenge.")
			self.keyInfo!.randomData1 = ucuFrame.randomData
			sendAppAuthorizationRequestWithRandom1()
		} else if ucuFrame.serviceId == "A857" && ucuFrame.subfunction == "0002" {
			print("[Validation] Step D: Received UCU response to our challenge.")
			if ucuFrame.randomData == self.keyInfo!.randomData2 {
				print("[Validation] Step E: Success! randomData2 matched. Authorization complete.")
				self.state = .connected
				if let peripheral = self.target?.peripheral {
					// NOW it's safe to discover control services
					discoverControlService(for: peripheral)
				}
			} else {
				print("[Validation] Step E: FAILED! randomData2 did not match.")
				self.disconnectPeripheral(peripheral: self.target?.peripheral)
			}
		} else {
			print("[Validation] FAILED! Unknown serviceId or subfunction.")
			self.disconnectPeripheral(peripheral: self.target?.peripheral)
		}
	}
	
	private func sendAppAuthorizationRequestWithRandom1() {
		guard let random1 = self.keyInfo?.randomData1,
			  let keyId = self.keyInfo?.keyIdHex,
			  let key = self.keyInfo?.aes128Key,
			  let target = self.target,
			  let requestChar = target.authorizeRequestCharacteristic else { return }
		
		let random2 = String(format: "%08X", arc4random())
		self.keyInfo?.randomData2 = random2
		
		print("[Validation] Step C: Sending App's challenge with randomData2: \(random2)")
		
		if let appFrame = AppAuthorizationRequestFrame(randomData2: random2, randomData1: random1, bleKeyId: keyId, key: key),
		   let dataToSend = appFrame.encryptedData {
			target.peripheral.writeValue(ofCharac: requestChar, value: dataToSend, type: .withResponse) { result in
				if case .failure(let error) = result {
					print("[BLE Error] Failed to send App challenge: \(error.localizedDescription)")
					self.disconnectPeripheral(peripheral: target.peripheral)
				}
			}
		}
	}
	
	private func discoverControlService(for peripheral: Peripheral) {
		print("BtThing: Step 6: Discovering control services after authorization...")
		peripheral.discoverServices(withUUIDs: [SGMWBLEProfile.ControlService.uuid]) { [weak self] result in
			guard let self = self else { return }
			if case .success(let services) = result, let service = services.first {
				peripheral.discoverCharacteristics(withUUIDs: SGMWBLEProfile.ControlService.Characteristics.AllCharacteristicsUuid, ofServiceWithUUID: service.uuid) { result in
					if case .success(let characteristics) = result {
						print("BtThing: Control service and characteristics are ready.")
						self.assignCharacteristics(characteristics)
					}
				}
			}
		}
	}
	
	private func assignCharacteristics(_ characteristics: [CBCharacteristic]) {
		for characteristic in characteristics {
			switch characteristic.uuid {
			case SGMWBLEProfile.AuthorizeService.Characteristics.Request.CBUUIDRepresentation:
				target?.authorizeRequestCharacteristic = characteristic
			case SGMWBLEProfile.AuthorizeService.Characteristics.Response.CBUUIDRepresentation:
				target?.authorizeResponseCharacteristic = characteristic
			case SGMWBLEProfile.ControlService.Characteristics.Request.CBUUIDRepresentation:
				target?.controlRequestCharacteristic = characteristic
			case SGMWBLEProfile.ControlService.Characteristics.Response.CBUUIDRepresentation:
				target?.controlResponseCharacteristic = characteristic
			default:
				break
			}
		}
	}
	
	private func disconnectPeripheral(peripheral: Peripheral?) {
		guard let peripheralToDisconnect = peripheral else { return }
		peripheralToDisconnect.disconnect { _ in
			// Actual cleanup is handled by the notification observer
			print("BtThing: disconnect command sent to \(peripheralToDisconnect.name ?? "unnamed")")
		}
	}
	
	@objc private func peripheralDidDisconnect(_ notification: Notification) {
		print("BtThing: target disconnected by notify")
		self.state = .disconnected
		self.target = nil
		self.authenticationMonitoringTask?.invalidate()
		self.authenticationMonitoringTask = nil
		
		if let peripheral = notification.object as? Peripheral {
			NotificationCenter.default.removeObserver(self, name: Peripheral.PeripheralDisconnected, object: peripheral)
			NotificationCenter.default.removeObserver(self, name: Peripheral.PeripheralCharacteristicValueUpdate, object: peripheral)
		}
	}
	
	private func getMacAddress(from manufacturerData: Data) -> String {
		guard manufacturerData.count >= 6 else { return "" }
		let macBytes = manufacturerData.suffix(6)
		return macBytes.hexEncodedString()
	}
}

// MARK: - App/UCU Data Frames (Unaltered)

/// App -> UCU 的授权请求帧
struct AppAuthorizationRequestFrame {
	let encryptedData: Data?
	init?(randomData2: String, randomData1: String, bleKeyId: String, key: Data) {
		let serviceId = "38C7", subfunction = "0002", payloadLength = "06"
		let randomData2Padded = randomData2.addZero(toLength: 8)
		let randomData1Padded = randomData1.addZero(toLength: 8)
		let bleKeyIdPadded = bleKeyId.addZero(toLength: 8)
		var sourceFrameString = "\(serviceId)\(subfunction)\(randomData2Padded)\(randomData1Padded)\(bleKeyIdPadded)\(payloadLength)"
		guard let sourceFrameData = sourceFrameString.dataFromHexString() else { return nil }
		let crc = sourceFrameData.crc16Checksum()
		let crcString = String(format: "%04X", crc).addZero(toLength: 4)
		var finalFrameString = sourceFrameString + crcString + String(repeating: "00", count: 7)
		guard let finalFrameData = finalFrameString.dataFromHexString() else { return nil }
		self.encryptedData = finalFrameData.aes128Encrypt(withKey: key)
	}
}

/// UCU -> App 的授权质询/响应帧
struct UcuAuthorizationRequestFrame {
	let serviceId: String, subfunction: String, randomData: String
	init?(dataFrame: Data, key: Data) {
		guard let decryptedData = dataFrame.aes128Decrypt(withKey: key) else { return nil }
		let decryptedString = decryptedData.hexEncodedString()
		guard decryptedString.count >= 20 else { return nil }
		self.serviceId = decryptedString.subString(from: 0, length: 4)
		self.subfunction = decryptedString.subString(from: 4, length: 4)
		self.randomData = decryptedString.subString(from: 8, length: 8)
	}
}

// MARK: - Helper Extensions (Unaltered)

fileprivate extension Data {
	func hexEncodedString() -> String { return map { String(format: "%02hhX", $0) }.joined() }
	func aes128Encrypt(withKey key: Data) -> Data? { return crypt(operation: CCOperation(kCCEncrypt), key: key) }
	func aes128Decrypt(withKey key: Data) -> Data? { return crypt(operation: CCOperation(kCCDecrypt), key: key) }
	private func crypt(operation: CCOperation, key: Data) -> Data? {
		var keyBytes = [UInt8](key), dataBytes = [UInt8](self)
		var buffer = [UInt8](repeating: 0, count: dataBytes.count + kCCBlockSizeAES128)
		var bufferLength = 0
		let status = CCCrypt(operation, CCAlgorithm(kCCAlgorithmAES), CCOptions(kCCOptionECBMode | kCCOptionPKCS7Padding), &keyBytes, key.count, nil, &dataBytes, dataBytes.count, &buffer, buffer.count, &bufferLength)
		return status == kCCSuccess ? Data(buffer.prefix(bufferLength)) : nil
	}
	func crc16Checksum() -> UInt16 {
		var crc: UInt16 = 0xFFFF, polynomial: UInt16 = 0xA001
		for byte in self {
			crc ^= UInt16(byte)
			for _ in 0..<8 { crc = (crc & 0x0001) != 0 ? (crc >> 1) ^ polynomial : crc >> 1 }
		}
		return crc
	}
}

fileprivate extension String {
	func dataFromHexString() -> Data? {
		var data = Data(capacity: self.count / 2)
		var index = self.startIndex
		while index < self.endIndex {
			let nextIndex = self.index(index, offsetBy: 2)
			if let b = UInt8(self[index..<nextIndex], radix: 16) { data.append(b) } else { return nil }
			index = nextIndex
		}
		return data
	}
	func addZero(toLength length: Int) -> String {
		var padded = self; while padded.count < length { padded = "0" + padded }; return padded
	}
	func subString(from: Int, length: Int) -> String {
		guard from < self.count, from + length <= self.count else { return "" }
		let start = self.index(self.startIndex, offsetBy: from)
		let end = self.index(start, offsetBy: length)
		return String(self[start..<end])
	}
}


// MARK: - Debug View (Unaltered)

#if DEBUG
struct BtDebugView: View {
	@StateObject var bt = BluetoothManager.shared
	
	var body: some View {
		NavigationView {
			List {
				Section(header: Text("Bluetooth")) {
					Text("Current State: \(bt.state.description)")
					Button("Start Scan", action: {
						bt.startScan()
					})
				}
				
				Section(header: Text("Discovered Peripherals")) {
					if bt.avaliblePeripherals.isEmpty {
						Text("None")
					} else {
						ForEach(bt.avaliblePeripherals) { peripheral in
							Text(peripheral.id)
						}
					}
				}
			}
			.navigationTitle("BT Debug")
		}
	}
}

#Preview {
	BtDebugView()
}
#endif
